# Database configuration
db.url: jdbc:postgresql://localhost:15432/FinancialTracker
db.username: username
db.password: password
db.pool.size: 10

db.liquibase.changelog: db/changelogs/changelog-master.yaml
db.liquibase.defaultSchema: supports
db.liquibase.mainSchema: entities